### ISSUE TITLE
Technically needs license for others to use

### ISSUE THREAD

**Issue by remyjette** [Overv/SteamWebAPI#9]
Hi there!

I like this API, but right now you haven't provided a license under which this source can be used.  If you could do so that'd be awesome!

**Comment by einsteinsci** [comment]
Agreed. Every GitHub project needs a license, and until this has one, nobody else can use it legally.

**Comment by Overv** [comment]
Sorry guys, I've added a licence.

You are however right about this project being abandoned. I'm afraid I don't have the time nor interest to continue developing this project, because I don't have a use case for it anymore.

I do know that the Steam app hasn't changed much either though. To what extend does this project still work?

**Comment by Overv** [comment]
I'm willing to invest some time in small fixes if needed.
